In [3]:
import numpy as np
from collections import namedtuple, deque

In [4]:
Label = [1, 2, 3]
JumpRates = [1, 1, 0.3]
Position = [(0,0), (2, 0), (0,1)]
Particles = zip (Label, JumpRates, Position)

In [61]:
Lx = 4
Ly = 2
mu = 0.5
sigma = 0.3
n = Lx*Ly // 2


Labels = [x+1 for x in range(n)]
JumpRates = np.zeros(n)
for i in range(n):
    JumpRates[i] = np.random.normal(mu, sigma)
    if JumpRates[i] > 1:
        JumpRates[i] = 1
    elif JumpRates[i] < 0:
        JumpRates[i] = 0    
Particles = list(zip (Labels, JumpRates))

In [62]:
# The first bracket gives you the location of the tuple in your list. The second bracket gives you the location of the item in the tuple.
Particles

[(1, 0.32337109532508),
 (2, 0.976357386789408),
 (3, 0.26284903914571894),
 (4, 0.5486655133277624)]

In [166]:
# Checkboard map generator
Map = np.zeros((Ly, Lx), dtype=int)  # Ly vectors with Lx (zero) components 
Map[::2, ::2] = 1  # Set even rows and even columns to 1
Map[1::2, 1::2] = 1  # Set odd rows and odd columns to 1

JumpRateGrid = np.ones((Ly, Lx), dtype=int)*(-0.001) # Ly vectors with Lx (zero) components

k = 0
for i in range(Ly):
    for j in range(Lx):
        if Map[i][j] == 1:
            Map[i][j] = Labels[k]
            JumpRateGrid[i][j] = JumpRates[k] 
            k += 1

In [167]:
Map

array([[1, 0, 2, 0],
       [0, 3, 0, 4]])

In [168]:
JumpRateGrid

array([[ 0.30682454, -0.001     ,  1.        , -0.001     ],
       [-0.001     ,  0.76133771, -0.001     ,  0.35815198]])

In [171]:
action = 2
for i in range(Ly):
    for j in range(Lx):
        label = Map[i, j]
        if label == action:
            X = i
            Y = j

In [172]:
X,Y

(0, 2)

In [142]:
# Checkboard system with labels and jumping rates together
System = np.zeros((Ly, Lx, 2))  # Ly set of Lx vectors with 2 components 
counter = 0
for i in range(Ly):
    if counter % 2 == 0:
        for j in range(0, Lx, 2):
            System[i][j][0] = 1
        for j in range(1, Lx, 2):
            System[i][j][0] = 0
    else:
        for j in range(0, Lx, 2):
            System[i][j][0] = 0
        for j in range(1, Lx, 2):
            System[i][j][0] = 1
    counter += 1
System

array([[[1., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.]]])

In [143]:
k = 0
for i in range(Ly):
    for j in range(Lx):
        if System[i][j][0] == 1:
            System[i][j] = Particles[k]
            k += 1

In [144]:
System

array([[[1.        , 0.3233711 ],
        [0.        , 0.        ],
        [2.        , 0.97635739],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [3.        , 0.26284904],
        [0.        , 0.        ],
        [4.        , 0.54866551]]])

In [162]:
Lx = 4
Ly = 2
mu = 0.5
sigma = 0.3
n = Lx*Ly // 2


Labels = [x+1 for x in range(n)]
JumpRates = np.zeros(n)
for i in range(n):
    JumpRates[i] = np.random.normal(mu, sigma)
    if JumpRates[i] > 1:
        JumpRates[i] = 1
    elif JumpRates[i] < 0:
        JumpRates[i] = 0    
Particles = list(zip (Labels, JumpRates))

# Random map generator
Map = np.concatenate((Label, np.zeros(Lx*Ly-n, int)))
np.random.shuffle(Map)
Map = Map.reshape((Ly, Lx))

In [163]:
Map

array([[1, 0, 0, 4],
       [2, 0, 3, 0]])

In [161]:
Particles

[(1, 0.656196735543812),
 (2, 0.4118415528530866),
 (3, 0.27764207143778724),
 (4, 0.9441319796294991)]

In [159]:
JumpRateGrid = np.zeros((Ly, Lx))
for i in range(Ly):
    for j in range(Lx):
        label = Map[i, j]
        if label != 0:
            # Find the corresponding JumpRate for the label
            JumpRateGrid[i, j] = Particles[label - 1][1]

In [160]:
JumpRateGrid

array([[0.65619674, 0.        , 0.        , 0.        ],
       [0.27764207, 0.        , 0.41184155, 0.94413198]])

In [164]:

k = 0
for i in range(Ly):
    for j in range(Lx):
        if System[i][j][0] == 1:
            System[i][j] = Particles[k]
            k += 1

In [165]:
System

array([[[1.        , 0.30682454],
        [0.        , 0.        ],
        [2.        , 0.97635739],
        [0.        , 0.        ]],

       [[0.        , 0.        ],
        [3.        , 0.26284904],
        [0.        , 0.        ],
        [4.        , 0.54866551]]])